#!/bin/bash
# Generated by claude-adapt init
# Triggers Phase 4 sync after a Claude Code session ends.
# This hook collects session insights and updates configuration.

set -e

# Check if claude-adapt is available
if ! command -v claude-adapt &> /dev/null; then
  # Try via npx
  npx claude-adapt sync --auto 2>/dev/null || true
else
  claude-adapt sync --auto 2>/dev/null || true
fi
