#!/bin/bash
# Generated by claude-adapt init
# Detected: Prettier + ESLint + Stylelint + TypeScript

set -e

STAGED=$(git diff --cached --name-only --diff-filter=ACMR)

if [ -z "$STAGED" ]; then
  echo "No staged files."
  exit 0
fi

# Type check
echo "Type checking..."
npx tsc --noEmit 2>/dev/null || {
  echo "Type errors found. Review before committing."
  exit 1
}

# Re-stage formatted/fixed files
echo "$STAGED" | xargs git add 2>/dev/null || true

echo "Pre-commit checks passed."
